version = 1

[[analyzers]]
name = "javascript"

  [analyzers.meta]
  environment = [
    "jquery",
    "nodejs",
    "browser",
    "jest",
    "mongo"
  ]

[[transformers]]
name = "standardjs"

[[transformers]]
name = "prettier"